investment/urls.py
from django.urls import path

from . import views

app_name = 'invest'

urlpatterns = [
    path('create/', views.create_form, name='create_invest'),
    path('preview/<int:id>', views.preview_invest, name='preview_invest'),
    path('review/<int:id>', views.review_invest, name='review_invest'),
    path('htmx-latest-rate/', views.htmx_latest_rate),
    path('htmx-create-invest/', views.htmx_create_invest),
]

result/urls.py
from django.urls import path

from . import views

app_name = 'result'

urlpatterns = [
    path('', views.result_index, name='result_index'),
    path('detail/<int:id>/', views.result_detail, name='result_detail'),
]

userprofile/urls.py
from django.urls import path

from . import views

app_name = 'profile'

urlpatterns = [
    path('', views.my_profile, name='my_profile'),
    path('account/', views.account_settings, name='account_settings'),
    path('settings/', views.profile_settings, name='profile_settings'),
    path(
        'settings/done/',
        views.profile_change_done,
        name='profile_change_done'),
    path('register/', views.RegisterCreateView.as_view(), name='register'),
    path('register/done/', views.register_done, name='register_done'),
    path('user/<str:slug>', views.user_profile, name='user_profile'),
]

userprofile/models.py
from PIL import Image 

from django.db import models
from django.contrib.auth.models import (
                                        AbstractBaseUser,
                                        BaseUserManager,
                                        PermissionsMixin
                                        )
from django.urls import reverse                                       


class MyUserManager(BaseUserManager):
    def create_user(self, email, user_name, password=None):

        if not email:
            raise ValueError('Users must have an email address')
        
        user = self.model(
            email=self.normalize_email(email),
            user_name=user_name,
        )

        user.set_password(password)
        user.save(using=self._db)
        return user
    
    def create_superuser(self, email, user_name, password=None):
        
        user = self.create_user(
            email,
            user_name,
            password=password,
        )
        user.is_admin = True
        user.save(using=self._db)
        return user


class MyUser(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(
        verbose_name='email address',
        max_length=255,
        unique=True,
    )
    user_name = models.CharField(max_length=50, unique=True)
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)
    join_date = models.DateTimeField(auto_now_add=True)

    objects = MyUserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['user_name']

    def __str__(self):
        return self.user_name

    def has_perm(self, perm, obj=None):
        return True

    def has_module_perms(self, app_label):
        return True

    @property
    def is_staff(self):
        return self.is_admin


class Profile(models.Model):
    user = models.ForeignKey(
        MyUser,
        on_delete=models.CASCADE,
        related_name='profile')
    slug = models.SlugField(max_length=50, unique=True)
    first_name = models.CharField(max_length=120, null=True)
    last_name = models.CharField(max_length=120, null=True)
    image = models.ImageField(
        blank=True,
        null=True,
        upload_to='profile_photos/%Y/%m/')
    about = models.TextField(max_length=2500, null=True, blank=True)

    def __str__(self):
        return self.user.user_name

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        if self.image:
            img = Image.open(self.image.path)
            if img.height > 300 or img.width > 300:
                output_size = (300, 300)
                img.thumbnail(output_size)
                img.save(self.image.path)

    def get_absolute_url(self):
        return reverse('userprofile:user_profile', kwargs={'user': self.slug})

userprofile/forms.py
from django import forms
from django.contrib.auth.forms import ReadOnlyPasswordHashField
from django.core.exceptions import ValidationError

from userprofile.models import MyUser, Profile


class UserCreationForm(forms.ModelForm):
    password1 = forms.CharField()
    password2 = forms.CharField()

    class Meta:
        model = MyUser
        fields = ('email', 'user_name')

    def clean_password2(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')
        if password1 and password2 and password1 != password2:
            raise ValidationError("Passwords don't match")
        return password2
    
    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password1'])
        if commit:
            user.save()
        return user


class UserChangeForm(forms.ModelForm):
    password = ReadOnlyPasswordHashField()

    class Meta:
        model = MyUser
        fields = ('email', 'user_name', 'password', 'is_active', 'is_admin')


class ProfileChangeForm(forms.ModelForm):

    class Meta:
        model = Profile
        fields = ('first_name', 'last_name', 'image', 'about')

userprofile/views.py
from django.shortcuts import redirect, render
from django.views.generic import CreateView

from investment.models import CreateInvest, ResultInvest
from userprofile.forms import UserCreationForm, ProfileChangeForm
from userprofile.models import MyUser, Profile


def my_profile(request):
    pending_advice = CreateInvest.objects.filter(
                                                investor=request.user,
                                                active=True)
    given_concluded_advice = ResultInvest.objects.filter(
                                                        investor=request.user)
    purchased_advice = MyUser.objects.get(user_name=request.user).invest.all()
    purchased_concluded_advice = (MyUser
                                  .objects
                                  .get(user_name=request.user)
                                  .member_result.all())

    context = {
        'pending_advice': pending_advice,
        'given_concluded_advice': given_concluded_advice,
        'purchased_advice': purchased_advice,
        'purchased_concluded_advice': purchased_concluded_advice,
    }
    return render(request, 'userprofile/my_profile.html', context)


class RegisterCreateView(CreateView):
    form_class = UserCreationForm
    template_name = 'registration/register.html'
    success_url = 'done/'


def register_done(request):
    return render(request, 'registration/register_done.html')


def user_profile(request, slug):
    user_profile = Profile.objects.get(slug=slug)
    pending_advice = CreateInvest.objects.filter(
        investor=user_profile.user.id,
        active=True
    )
    concluded_advice = ResultInvest.objects.filter(
        investor=user_profile.user.id)
    
    context = {
        'user_profile': user_profile,
        'pending_advice': pending_advice,
        'concluded_advice': concluded_advice,
    }
    return render(request, 'userprofile/user_profile.html', context)

def account_settings(request):
    return render(request, 'userprofile/account_settings.html')

def profile_settings(request):
    user_profile = Profile.objects.get(user=request.user)
    form = ProfileChangeForm(instance=user_profile)

    if request.method == "POST":
        form = ProfileChangeForm(request.POST,
                                 request.FILES,
                                 instance=user_profile)
        if form.is_valid():
            form.save()
            return redirect('profile:profile_change_done')

    context = {
        'form': form,
        'user_profile': user_profile,
    }
    return render(request, 'userprofile/profile_settings.html', context)

def profile_change_done(request):
    return render(request, 'userprofile/profile_change_done.html')

userprofile/templates/userprofile/account_settings.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-4">
            <div class="d-grid gap-2">
                <h1 class="h3 mb-3 fw-normal text-center text-light">
                    Account Settings
                </h1>
                <hr>
                <a href="{% url 'password_change' %}" class="btn btn-outline-warning">Change Password</a>
                <a href="{% url 'profile:profile_settings' %}" class="btn btn-outline-warning">Change Profile</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

userprofile/templates/userprofile/my_profile.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-6">
            <div class="row">
                <div class="alert alert-secondary text-light fw-bold text-center fs-4 bg-transparent">
                    Given Advices
                </div>
                <div class="col-6">
                    <div class="alert alert-secondary text-light fw-bold text-center fs-6 bg-transparent">
                        Pending
                    </div>
                    <table class="table table-sm table-borderless table-hover border-secondary">
                        <thead class="text-light">
                            <tr>
                                <th>Advice</th>
                                <th>Target Date</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for i in pending_advice %}
                            <tr>
                                <td><a class="text-secondary" href="{% url 'invest:review_invest' i.id %}" style="text-decoration: none;">{{i.base_currency}} to {{i.target_currency}}</a></td>
                                <td class="text-secondary">{{i.target_date}}</td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
                <div class="col-6">
                    <div class="alert alert-secondary text-light fw-bold text-center fs-6 bg-transparent">
                        Concluded
                    </div>
                    <table class="table table-sm table-borderless table-hover border-secondary">
                        <thead class="text-light">
                            <tr>
                                <th>Advice</th>
                                <th>Ratio</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for i in given_concluded_advice %}
                            <tr>
                                <td><a class="text-secondary" href="{% url 'result:result_detail' i.id %}" style="text-decoration: none;">{{i.invest.base_currency}} to {{i.invest.target_currency}}</a></td>
                                <td class="text-secondary">%{{i.ratio}}</td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-6">
            <div class="row">
                <div class="alert alert-secondary text-light fw-bold text-center fs-4 bg-transparent">
                    Purchased Advices
                </div>
                <div class="col-6">
                    <div class="alert alert-secondary text-light fw-bold text-center fs-6 bg-transparent">
                        Pending
                    </div>
                    <table class="table table-sm table-borderless table-hover border-secondary">
                        <thead class="text-light">
                            <tr>
                                <th>Advice</th>
                                <th>Target Date</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for i in purchased_advice %}
                            <tr>
                                <td><a class="text-secondary" href="{% url 'invest:review_invest' i.id %}" style="text-decoration: none;">{{i.base_currency}} to {{i.target_currency}}</a></td>
                                <td class="text-secondary">{{i.target_date}}</td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
                <div class="col-6">
                    <div class="alert alert-secondary text-light fw-bold text-center fs-6 bg-transparent">
                        Concluded
                    </div>
                    <table class="table table-sm table-borderless table-hover border-secondary">
                        <thead class="text-light">
                            <tr>
                                <th>Advice</th>
                                <th>Ratio</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for i in purchased_concluded_advice %}
                            <tr>
                                <td><a class="text-secondary" href="{% url 'result:result_detail' i.id %}" style="text-decoration: none;">{{i.invest.base_currency}} to {{i.invest.target_currency}}</a></td>
                                <td class="text-secondary">%{{i.ratio}}</td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

userprofile/templates/userprofile/profile_change_done.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="row justify-content-md-center">
        <div class="col-4">
            <h1 class="h3 mb-3 fw-normal text-center text-light">
                Profile settings has been changed.
            </h1>
        </div>
    </div>
</div>
{% endblock %}

userprofile/templates/userprofile/profile_settings.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-6">
            <div class="row justify-content-md-center">
                <div class="card mb-3 bg-transparent text-light" style="max-width: 540px;">
                  <div class="row g-0">
                    <div class="col-md-4">
                      <img src="{% if user_profile.image %} {{user_profile.image.url}} {% else %} {{'https://seeklogo.com/images/D/django-logo-4C5ECF7036-seeklogo.com.png'}} {% endif%}" class="rounded-circle" alt=" " width="180" height="180">
                    </div>
                    <div class="col-md-8">
                      <div class="card-body">
                        <h5 class="card-title">{{user_profile.user}}</h5>
                        <p class="card-text">Name: {{user_profile.first_name}} {{user_profile.last_name}}</p>
                        <p class="card-text"><small class="text-muted">{{user_profile.about}}</small></p>
                      </div>
                    </div>
                  </div>
                </div>
            </div>
        </div>
        <div class="col-4">
            <div class="d-grid gap-2">
                <h1 class="h3 mb-3 fw-normal text-center text-light">
                    Profile Settings
                </h1>
                <hr>
                <form method="POST" enctype="multipart/form-data">
                    {% render_field form.first_name class="form-control" placeholder="First Name" required="false" %}
                    <br>
                    {% render_field form.last_name class="form-control" placeholder="Last Name" type="text" %}
                    <br>
                    {% render_field form.image class="form-control"%}
                    <br>
                    {% render_field form.about class="form-control" placeholder="About" type="text" %}
                    <br>
                    <div class="d-grid gap-2">
                        <button class="btn btn-outline-warning" type="submit">Change</button>
                    </div>
                    {% csrf_token %}
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

userprofile/templates/userprofile/user_profile.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
  <div class="row justify-content-md-center">
    <div class="card mb-3 bg-transparent text-light" style="max-width: 540px;">
      <div class="row g-0">
        <div class="col-md-4">
          <img src="{% if user_profile.image %} {{user_profile.image.url}} {% else %} {{'https://seeklogo.com/images/D/django-logo-4C5ECF7036-seeklogo.com.png'}} {% endif%}" class="rounded-circle" alt=" " width="180" height="180">
        </div>
        <div class="col-md-8">
          <div class="card-body">
            <h5 class="card-title">{{user_profile.user}}</h5>
            <p class="card-text">Name: {{user_profile.first_name}} {{user_profile.last_name}}</p>
            <p class="card-text"><small class="text-muted">{{user_profile.about}}</small></p>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-6">
      <div class="alert alert-secondary text-light fw-bold text-center fs-4 bg-transparent">
        Pending Advices
      </div>
      <table class="table table-sm table-borderless table-hover border-secondary">
        <thead class="text-light">
          <tr>
            <th scope="col">Advice</th>
            <th scope="col">Target Date</th>
            <th scope="col">Owners</th>
          </tr>
        </thead>
        <tbody>
          {% for i in pending_advice %}
          <tr>
            <td><a class="text-secondary" style="text-decoration: none;" href="{% url 'invest:preview_invest' i.id %}">Go to Advice</a></td>
            <td class="text-secondary">{{i.target_date}}</td>
            <td class="text-secondary">{{i.member.count}}</td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
    <div class="col-6">
      <div class="alert alert-secondary text-light fw-bold text-center fs-4 bg-transparent">
        Concluded Advices
      </div>
      <table class="table table-sm table-borderless table-hover border-secondary">
        <thead class="text-light">
          <tr>
            <th scope="col">Advice</th>
            <th scope="col">Total</th>
            <th scope="col">Ratio</th>
            <th scope="col">Owners</th>
          </tr>
        </thead>
        <tbody>
          {% for i in concluded_advice %}
          <tr>
            <td><a class="text-secondary" style="text-decoration: none;" href="{% url 'result:result_detail' i.id %}">{{i.invest.base_currency}} to {{i.invest.target_currency}}</a></td>
            {% if i.total_value > 0 %}
            <td class="text-success">{{i.total_value}}</td>
            <td class="text-success">% {{i.ratio|truncatechars:6}}</td>
            {% else %}
            <td class="text-danger">{{i.total_value}}</td>
            <td class="text-danger">% {{i.ratio|truncatechars:6}}</td>
            {% endif %}
            <td class="text-secondary">{{i.member.count}}</td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
</div>
{% endblock %}