result/urls.py
from django.urls import path

from . import views

app_name = 'result'

urlpatterns = [
    path('', views.result_index, name='result_index'),
    path('detail/<int:id>/', views.result_detail, name='result_detail'),
]

userprofile/urls.py
from django.urls import path

from . import views

app_name = 'profile'

urlpatterns = [
    path('', views.my_profile, name='my_profile'),
    path('account/', views.account_settings, name='account_settings'),
    path('settings/', views.profile_settings, name='profile_settings'),
    path(
        'settings/done/',
        views.profile_change_done,
        name='profile_change_done'),
    path('register/', views.RegisterCreateView.as_view(), name='register'),
    path('register/done/', views.register_done, name='register_done'),
    path('user/<str:slug>', views.user_profile, name='user_profile'),
]

result/models.py
from django.db import models

# Create your models here.

result/views.py
from django.shortcuts import render

from investment.models import ResultInvest


def result_index(request):
    invest_result = ResultInvest.objects.all()
    top_earner = ResultInvest.objects.order_by('-total_value')

    context = {
        'invest_result': invest_result,
        'top_earner': top_earner,
    }
    return render(request, 'result/result_index.html', context)


def result_detail(request, id):
    invest_result = ResultInvest.objects.get(id=id)

    context = {
        'invest_result': invest_result,
    }
    return render(request, 'result/result_detail.html', context)

result/templates/result/result_detail.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
  <div class="row justify-content-center">
    <div class="col-12">
      <div class="alert text-center text-light fw-bold fs-4">{{invest_result.invest.base_currency}} to {{invest_result.invest.target_currency}}</div>
      <table class="table table-sm table-borderless border-secondary">
        <thead class="text-secondary">
          <tr>
            <th>Create Date</th>
            <th>Finish Date</th>
            <th>Advisor</th>
            <th>Start Value</th>
            <th>Final Value</th>
            <th>Total Value</th>
            <th>Ratio</th>
            <th>Owners</th>
          </tr>
        </thead>
        <tbody class="text-light fw-bold">
          <tr>
            <td>{{invest_result.invest.create_time|date}}</td>
            <td>{{invest_result.invest.target_date}}</td>
            <td><a style="text-decoration: none;" href="{% url 'profile:user_profile' invest_result.investor|lower %}">{{invest_result.investor}}</a></td>
            <td>{{invest_result.start_value}}</td>
            <td>{{invest_result.result_value}}</td>
            {% if invest_result.total_value > 0 %}
            <td class="text-success">{{invest_result.total_value}}</td>
            <td class="text-success">% {{invest_result.ratio}}</td>
            {% else %}
            <td class="text-danger">{{invest_result.total_value}}</td>
            <td class="text-danger">% {{invest_result.ratio}}</td>
            {% endif %}
            <td>{{invest_result.member.count}}</td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>
{% endblock %}

result/templates/result/result_index.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col">
            <div class="alert alert-secondary text-light fw-bold text-center fs-4 bg-transparent">
                 Daily Results
            </div>
            <table class="table table-sm table-borderless table-hover border-secondary">
                <thead class="text-light">
                    <tr>
                        <th scope="col">Advice</th>
                        <th scope="col">Advisor</th>
                        <th scope="col">Total</th>
                        <th scope="col">Ratio</th>
                    </tr>
                </thead>
                <tbody>
                    {% for i in invest_result %}
                    <tr>
                        <td><a class="text-secondary" style="text-decoration: none;" href="{% url 'result:result_detail' i.id %}">{{i.invest.base_currency}} to {{i.invest.target_currency}}</a></td>
                        <td><a class="text-primary" style="text-decoration: none;" href="{% url 'profile:user_profile' i.investor|lower %}">{{i.investor|truncatechars:10}}</a></td>
                        {% if i.total_value > 0 %}
                        <td class="text-success">{{i.total_value}}</td>
                        <td class="text-success">% {{i.ratio|truncatechars:6}}</td>
                        {% else %}
                        <td class="text-danger">{{i.total_value}}</td>
                        <td class="text-danger">% {{i.ratio|truncatechars:6}}</td>
                        {% endif %}
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="col">
            <div class="alert alert-secondary text-light fw-bold text-center fs-4 bg-transparent">
                Daily Top Earners
            </div>
            <table class="table table-sm table-borderless table-hover border-secondary">
                <thead class="text-light">
                    <tr>
                        <th scope="col">Advice</th>
                        <th scope="col">Advisor</th>
                        <th scope="col">Total</th>
                        <th scope="col">Ratio</th>
                    </tr>
                </thead>
                <tbody>
                    {% for i in top_earner %}
                    <tr>
                        <td><a class="text-secondary" style="text-decoration: none;" href="{% url 'result:result_detail' i.id %}">{{i.invest.base_currency}} to {{i.invest.target_currency}}</a></td>
                        <td><a class="text-primary" style="text-decoration: none;" href="{% url 'profile:user_profile' i.investor|lower %}">{{i.investor|truncatechars:10}}</a></td>
                        {% if i.total_value > 0 %}
                        <td class="text-success">{{i.total_value}}</td>
                        <td class="text-success">% {{i.ratio|truncatechars:6}}</td>
                        {% else %}
                        <td class="text-danger">{{i.total_value}}</td>
                        <td class="text-danger">% {{i.ratio|truncatechars:6}}</td>
                        {% endif %}
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>

{% endblock %}