finance/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('', views.index, name='index'),
    path('htmx-latest-advices/', views.htmx_latest_advices),
    path('htmx-popular-advices/', views.htmx_popular_advices),
]

investment/urls.py
from django.urls import path

from . import views

app_name = 'invest'

urlpatterns = [
    path('create/', views.create_form, name='create_invest'),
    path('preview/<int:id>', views.preview_invest, name='preview_invest'),
    path('review/<int:id>', views.review_invest, name='review_invest'),
    path('htmx-latest-rate/', views.htmx_latest_rate),
    path('htmx-create-invest/', views.htmx_create_invest),
]

payment/urls.py
from django.urls import path

from payment import views


app_name = 'payment'

urlpatterns = [
    path(
        'purchaseoption/',
        views.purchasing_option,
        name='purchasing_option'
    ),
    path('process/<int:id>/', views.payment_process, name='process'),
    path('canceled/', views.payment_canceled, name='canceled'),
    path('done/', views.payment_done, name='done'),
]

result/urls.py
from django.urls import path

from . import views

app_name = 'result'

urlpatterns = [
    path('', views.result_index, name='result_index'),
    path('detail/<int:id>/', views.result_detail, name='result_detail'),
]

userprofile/urls.py
from django.urls import path

from . import views

app_name = 'profile'

urlpatterns = [
    path('', views.my_profile, name='my_profile'),
    path('account/', views.account_settings, name='account_settings'),
    path('settings/', views.profile_settings, name='profile_settings'),
    path(
        'settings/done/',
        views.profile_change_done,
        name='profile_change_done'),
    path('register/', views.RegisterCreateView.as_view(), name='register'),
    path('register/done/', views.register_done, name='register_done'),
    path('user/<str:slug>', views.user_profile, name='user_profile'),
]

finance/models.py
from django.db import models

# Create your models here.

finance/views.py
from django.shortcuts import render
from django.db.models import Count
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from investment.models import CreateInvest


def index(request):
    latest_advices = (CreateInvest
                      .objects
                      .filter(active=True)
                      .order_by('-create_time'))
    popular_advices = (CreateInvest
                       .objects
                       .filter(active=True)
                       .annotate(q_count=Count('member'))
                       .order_by('-q_count'))

    context = {
        'latest_advices': latest_advices,
        'popular_advices': popular_advices,
    }
    return render(request, 'index.html', context)


def htmx_latest_advices(request):
    latest_advices = (CreateInvest
                      .objects
                      .filter(active=True)
                      .order_by('-create_time'))

    paginator = Paginator(latest_advices, 8)
    page = request.GET.get('page')
    try:
        paginate_advices = paginator.page(page)
    except PageNotAnInteger:
        paginate_advices = paginator.page(1)
    except EmptyPage:
        paginate_advices = paginator.page(paginator.num_pages)

    context = {
        'latest_advices': latest_advices,
        'paginate_advices': paginate_advices,
    }
    return render(request, 'htmx_latest_advices.html', context)


def htmx_popular_advices(request):
    popular_advices = (CreateInvest
                      .objects
                      .filter(active=True)
                      .annotate(q_count=Count('member'))
                      .order_by('-q_count'))

    paginator = Paginator(popular_advices, 8)
    page = request.GET.get('page')
    try:
        paginate_advices = paginator.page(page)
    except PageNotAnInteger:
        paginate_advices = paginator.page(1)
    except EmptyPage:
        paginate_advices = paginator.page(paginator.num_pages)

    context = {
        'popular_advices': popular_advices,
        'paginate_advices': paginate_advices,
    }
    return render(request, 'htmx_popular_advices.html', context)

finance/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
</head>

<body style="background-color: rgb(22, 26, 30);">

  <div class="container">
    <header
      class="d-flex flex-wrap align-items-center justify-content-center justify-content-md-between py-3 mb-4 border-bottom">
      <a href="{% url 'index' %}"
        class="d-flex align-items-center col-md-3 mb-2 mb-md-0 text-success text-decoration-none fs-2 fw-bold">
        FinDjango
      </a>

      <ul class="nav col-12 col-md-auto mb-2 justify-content-center mb-md-0">
        <li><a href="{% url 'index' %}" class="nav-link px-3 link-light fw-bold">Home</a></li>
        <li><a href="{% url 'invest:create_invest' %}" class="nav-link px-3 link-light fw-bold">Create Advice</a></li>
        <li><a href="{% url 'result:result_index' %}" class="nav-link px-3 link-light fw-bold">Results</a></li>
        <li><a href="{% url 'payment:purchasing_option' %}" class="nav-link px-3 link-light fw-bold">Get Token</a></li>
        {% if request.user.is_authenticated %}
        <li><a href="{% url 'profile:my_profile' %}" class="nav-link px-3 link-light fw-bold">Profile</a></li>
        {% endif %}
      </ul>
      
      {% if request.user.is_authenticated %}
      <span class="text-warning">Token: {{user_token}}</span>
      <div class="dropdown">
        <button class="btn btn-outline-warning dropdown-toggle" type="button" id="dropdownMenuButton2" data-bs-toggle="dropdown" aria-expanded="false">
          {{request.user|truncatechars:15}}
        </button>
        <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="dropdownMenuButton2">
          <li><a class="dropdown-item" href="{% url 'profile:my_profile' %}">Profile</a></li>
          <li><a class="dropdown-item" href="{% url 'profile:account_settings' %}">Settings</a></li>
          <li><hr class="dropdown-divider"></li>
          <li><a class="dropdown-item text-warning" href="{% url 'logout' %}">Logout</a></li>
        </ul>
      </div>
      {% else %}
      <div class="col-md-3 text-end">
        <a href="{% url 'login' %}" class="btn btn-outline-warning me-2">Login</a>
        <a href="{% url 'profile:register' %}" class="btn btn-outline-warning me-2">Sign-up</a>
      </div>
      {% endif %}
    </header>
  </div>

  {% block content %}
  {% endblock %}

  <div class="container">
    <footer class="py-3 my-4">
      <ul class="nav justify-content-center border-bottom pb-3 mb-3">
        <li class="nav-item"><a href="/" class="nav-link px-2 text-muted">Home</a></li>
        <li class="nav-item"><a href="https://github.com/karadenizas" class="nav-link px-2 text-muted">GitHub</a></li>
        <li class="nav-item"><a href="https://twitter.com/askaradeniz" class="nav-link px-2 text-muted">Twitter</a></li>
        <li class="nav-item"><a href="https://www.linkedin.com/in/askaradeniz" class="nav-link px-2 text-muted">LinkedIn</a></li>
      </ul>
      <p class="text-center text-muted">&copy; 2021 <strong>FinDjango</strong></p>
    </footer>
  </div>

  <script src="https://unpkg.com/htmx.org@1.6.1"></script>  
  <script src="{% static 'js/bootstrap.bundle.js' %}"></script>
</body>

</html>

finance/templates/htmx_latest_advices.html
<div class="d-grid gap-2" id="latestAdvices">
    <button id="latestButton" hx-get="/htmx-latest-advices" hx-target="#latestAdvices"
        class="btn btn-outline-secondary text-light" type="button">Latest Advices
        <svg xmlns="http://www.w3.org/2000/svg" width="15" height="15" fill="currentColor"
            class="bi bi-arrow-clockwise" viewBox="0 0 16 16">
            <path fill-rule="evenodd" d="M8 3a5 5 0 1 0 4.546 2.914.5.5 0 0 1 .908-.417A6 6 0 1 1 8 2v1z" />
            <path
                d="M8 4.466V.534a.25.25 0 0 1 .41-.192l2.36 1.966c.12.1.12.284 0 .384L8.41 4.658A.25.25 0 0 1 8 4.466z" />
        </svg>
    </button>
    {% for i in paginate_advices %}
    <a class="btn btn-outline-secondary text-light" type="submit" href="{% url 'invest:preview_invest' i.id %}">
        <span class="">{{i.investor|truncatechars:12}}</span>
        <span class="fw-light">{{i.target_date}}</span>
    </a>
    {% endfor %}
    {% include 'latest_pagination.html' with page=paginate_advices %}
</div>

finance/templates/htmx_popular_advices.html
<div class="d-grid gap-2" id="popularAdvices">
    <button id="popularButton" hx-get="/htmx-popular-advices" hx-target="#popularAdvices"
        class="btn btn-outline-secondary text-light" type="button">Popular Advices
        <svg xmlns="http://www.w3.org/2000/svg" width="15" height="15" fill="currentColor"
            class="bi bi-arrow-clockwise" viewBox="0 0 16 16">
            <path fill-rule="evenodd" d="M8 3a5 5 0 1 0 4.546 2.914.5.5 0 0 1 .908-.417A6 6 0 1 1 8 2v1z" />
            <path
                d="M8 4.466V.534a.25.25 0 0 1 .41-.192l2.36 1.966c.12.1.12.284 0 .384L8.41 4.658A.25.25 0 0 1 8 4.466z" />
        </svg>
    </button>
    {% for i in paginate_advices %}
    <a class="btn btn-outline-secondary text-light" type="submit" href="{% url 'invest:preview_invest' i.id %}">
        <span class="">{{i.investor|truncatechars:12}}</span>
        <span class="fw-light">{{i.target_date}}</span>
    </a>
    {% endfor %}
    {% include 'popular_pagination.html' with page=paginate_advices %}
</div>

finance/templates/index.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-3">
            {% include 'htmx_latest_advices.html' %}
        </div>
        <div class="col-6">
            <div class="card bg-transparent">
                <div class="card-body text-center">
                    <h5 class="card-title text-light">Welcome to FinDjango</h5>
                    <p class="card-text text-light">
                        FinDjango is <strong>sample/test</strong> financial consultancy application.
                        <br>
                        Here you can get advice or give advice.
                        If you want to use the app you have must be login!
                    </p>
                </div>
            </div>
            <div class="accordion" id="accordionExample">
                <div class="accordion-item bg-transparent border-secondary">
                    <h2 class="accordion-header" id="headingOne">
                        <button class="accordion-button bg-transparent text-secondary" type="button"
                            data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true"
                            aria-controls="collapseOne">
                            <strong>How can I take an advice?</strong>
                        </button>
                    </h2>
                    <div id="collapseOne" class="accordion-collapse collapse text-light" aria-labelledby="headingOne"
                        data-bs-parent="#accordionExample">
                        <div class="accordion-body">
                            <ul>
                                <li>Click on Get Token and choose a package and go to the payment screen.</li>
                                <li>Enter the card number as 4111 1111 1111 1111. Enter a random number in the other
                                    fields.</li>
                                <li>The token will be loaded into your account.</li>
                                <li>Select and buy one of the advices on the homepage.</li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="accordion-item bg-transparent border-secondary">
                    <h2 class="accordion-header" id="headingTwo">
                        <button class="accordion-button bg-transparent text-secondary" type="button"
                            data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="true"
                            aria-controls="collapseTwo">
                            <strong>How can I give an advice?</strong>
                        </button>
                    </h2>
                    <div id="collapseTwo" class="accordion-collapse collapse text-light" aria-labelledby="headingTwo"
                        data-bs-parent="#accordionExample">
                        <div class="accordion-body">
                            <ul>
                                <li>Click on Create Advice.</li>
                                <li>The first currency must gain value against the second currency of the target date.
                                </li>
                                <li>Select the target date.</li>
                                <li>Write the info.</li>
                                <li>Write the analysis that buyers will see.</li>
                                <li>Enter the token amount.</li>
                                <li>And create.</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-3">
            {% include 'htmx_popular_advices.html' %}
        </div>
    </div>
</div>

<!-- doen't show the advices when loaded the page .solution for now. -->
<script type="text/javascript">
    window.onload=function() {
      document.getElementById("popularButton").click()
      document.getElementById("latestButton").click()
    }
</script>

<!-- <div class="container">
    <div class="row">
        <div class="col-3">
            <div class="alert alert-secondary fs-4 text-center" role="alert">
                Latest Advices
            </div>
            <table class="table table-sm table-bordered border-secondary">
                <thead>
                    <tr>
                        <th scope="col">Advisor</th>
                        <th scope="col">Target Date</th>
                    </tr>
                </thead>
                <tbody>
                    {% for i in latest_advices %}
                    <tr>
                        <td><a href="{% url 'investment:preview_invest' i.id %} ">{{i.investor}}</a></td>
                        <td>{{i.target_date}}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="col-6">
            <div class="card text-center">
                <div class="card-header">
                  Wellcome to FinDjango!
                </div>
                <div class="card-body">
                  <h5 class="card-title text-blue">FinDjango is financial consultancy app.</h5>
                  <p class="card-text">Here you can get advice or give advice.</p>
                </div>
            </div>
            <br>
        </div>
        <div class="col-3">
            <div class="alert alert-secondary fs-4 text-center" role="alert">
                Popular Advices
            </div>
            <table class="table table-sm table-bordered border-secondary">
                <thead>
                    <tr>
                        <th scope="col">Advisor</th>
                        <th scope="col">Owners</th>
                    </tr>
                </thead>
                <tbody>
                    {% for i in popular_advices %}
                    <tr>
                        <td><a href="{% url 'investment:preview_invest' i.id %} ">{{i.investor}}</a></td>
                        <td class="text-center">{{i.member.count}}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div> -->
{% endblock %}

finance/templates/latest_pagination.html
<div class="btn-group" role="group">

  {% if page.has_previous %}
  <button type="button" class="btn btn-outline-secondary"
          hx-target="#latestAdvices" hx-get="/htmx-latest-advices/?page={{ page.previous_page_number }}">
          Back
  </button>
  {% else %}
  <button type="button" class="btn btn-outline-secondary disabled">Back</button>
  {% endif %}

  <button type="button" class="btn btn-outline-secondary">{{page.number}}</button>
  <button type="button" class="btn btn-outline-secondary"
          hx-target="#latestAdvices" hx-get="/htmx-latest-advices/?page={{ page.paginator.num_pages }}">
          {{page.paginator.num_pages}}
  </button>

  {% if page.has_next %}
  <button type="button" class="btn btn-outline-secondary"
          hx-target="#latestAdvices" hx-get="/htmx-latest-advices/?page={{ page.next_page_number }}">
          Next
  </button>
  {% else %}
  <button type="button" class="btn btn-outline-secondary disabled">Next</button>
  {% endif %}
  
</div>

finance/templates/popular_pagination.html
<div class="btn-group" role="group">

    {% if page.has_previous %}
    <button type="button" class="btn btn-outline-secondary"
            hx-target="#popularAdvices" hx-get="/htmx-popular-advices/?page={{ page.previous_page_number }}">
            Back
    </button>
    {% else %}
    <button type="button" class="btn btn-outline-secondary disabled">Back</button>
    {% endif %}
  
    <button type="button" class="btn btn-outline-secondary">{{page.number}}</button>
    <button type="button" class="btn btn-outline-secondary"
            hx-target="#popularAdvices" hx-get="/htmx-popular-advices/?page={{ page.paginator.num_pages }}">
            {{page.paginator.num_pages}}
    </button>
  
    {% if page.has_next %}
    <button type="button" class="btn btn-outline-secondary"
            hx-target="#popularAdvices" hx-get="/htmx-popular-advices/?page={{ page.next_page_number }}">
            Next
    </button>
    {% else %}
    <button type="button" class="btn btn-outline-secondary disabled">Next</button>
    {% endif %}
    
  </div>