payment/urls.py
from django.urls import path

from payment import views


app_name = 'payment'

urlpatterns = [
    path(
        'purchaseoption/',
        views.purchasing_option,
        name='purchasing_option'
    ),
    path('process/<int:id>/', views.payment_process, name='process'),
    path('canceled/', views.payment_canceled, name='canceled'),
    path('done/', views.payment_done, name='done'),
]

result/urls.py
from django.urls import path

from . import views

app_name = 'result'

urlpatterns = [
    path('', views.result_index, name='result_index'),
    path('detail/<int:id>/', views.result_detail, name='result_detail'),
]

payment/models.py
from django.db import models

from userprofile.models import MyUser


class UserWallet(models.Model):
    user = models.ForeignKey(
        MyUser,
        on_delete=models.CASCADE,
        related_name='wallet'
    )
    token = models.IntegerField(default=0)

    def __str__(self):
        return self.user.user_name


class PaymentTransaction(models.Model):
    wallet = models.ForeignKey(
        UserWallet,
        on_delete=models.CASCADE,
        related_name='transactions')
    transaction_type = models.CharField(
        max_length=10,
        choices=(
        ('buy', 'Buying Transactions'), ('sell', 'Selling Transactions'),))
    braintree_id = models.CharField(max_length=150, blank=True)
    # you can change the other integerfields to positiveintegerfield
    amount = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.wallet.user.user_name


class PurchaseOption(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField(max_length=500, default='')
    token_amount = models.IntegerField(default=0)
    token_price = models.DecimalField(
        max_digits=5, decimal_places=2, default=0)
    total_price = models.DecimalField(
        max_digits=7, decimal_places=2, default=0)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.total_price = self.token_amount * self.token_price
        return super().save(*args, **kwargs)

payment/views.py
import braintree

from django.shortcuts import redirect, render
from django.conf import settings

from payment.models import PurchaseOption, UserWallet, PaymentTransaction


gateway = braintree.BraintreeGateway(settings.BRAINTREE_CONF)


def purchasing_option(request):
    packs = PurchaseOption.objects.all()

    context = {
        'packs':packs,
    }
    return render(request, 'payment/purchasing_option.html', context)

def payment_process(request, id):
    if request.method == "POST":
        pack = PurchaseOption.objects.get(id=id)
        user_wallet = UserWallet.objects.get(user=request.user)

        # start the process
        nonce = request.POST.get('payment_method_nonce', None)
        result = gateway.transaction.sale({
            'amount': pack.total_price,
            'payment_method_nonce': nonce,
            'options': {'submit_for_settlement': True}
        })
        
        if result.is_success:
            PaymentTransaction.objects.create(
                wallet=user_wallet,
                transaction_type='buy',
                braintree_id=result.transaction.id,
                amount=pack.token_amount
                )
            user_wallet.braintree_id = result.transaction.id
            user_wallet.token += pack.token_amount
            user_wallet.save()
            return redirect('payment:done')
        else:
            return redirect('payment:canceled')
    else:
        client_token = gateway.client_token.generate()
        context = {
            'client_token': client_token
        }
        return render(request, 'payment/process.html', context)


def payment_done(request):
    return render(request, 'payment/done.html')


def payment_canceled(request):
    return render(request, 'payment/canceled.html')

payment/templates/payment/canceled.html
{% extends 'base.html' %}

{% block content %}
<div class="container text-center">
    <div class="alert alert-danger" role="alert">
        Your payment has not been processed!
      </div>
</div>
{% endblock %}

payment/templates/payment/done.html
{% extends 'base.html' %}

{% block content %}
<div class="container text-center">
    <div class="text-success fw-bold bg-transparent">
        Your payment was successful!
      </div>
</div>
{% endblock %}

payment/templates/payment/process.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<link rel="stylesheet" href="{% static 'css/braintree.css' %}">

<div class="container">
    <div class="row justify-content-center">
        <div class="col-4">
            <div class="demo-frame">  
                <form method="post" id="payment">
                <label class="hosted-fields--label text-light" for="card-number">Card Number</label>
                <div id="card-number" class="hosted-field"></div>
              
                <label class="hosted-fields--label text-light" for="expiration-date">Expiration Date</label>
                <div id="expiration-date" class="hosted-field"></div>
              
                <label class="hosted-fields--label text-light" for="cvv">CVV</label>
                <div id="cvv" class="hosted-field"></div>
              
                <div class="button-container">
                <input type="hidden" id="nonce" name="payment_method_nonce" value="">
                <input type="submit" class="button button--small button--green text-dark fw-bold" value="Purchase"/>
                </div>
                {% csrf_token %}
                </form>
              </div>
              <script src="https://js.braintreegateway.com/web/3.58.0/js/client.min.js"></script>
              <script src="https://js.braintreegateway.com/web/3.58.0/js/hosted-fields.min.js"></script>
              <script>
                var form = document.querySelector('#payment');
                var submit = document.querySelector('input[type="submit"]');
            
                braintree.client.create({
                  authorization: '{{ client_token }}'
                }, function (clientErr, clientInstance) {
                  if (clientErr) {
                    console.error(clientErr);
                    return;
                  }
            
                  braintree.hostedFields.create({
                    client: clientInstance,
                    styles: {
                      'input': {'font-size': '16px'},
                      'input.invalid': {'color': 'red'},
                      'input.valid': {'color': 'green'}
                    },
                    fields: {
                      number: {selector: '#card-number', placeholder: '4111 1111 1111 1111'},
                      cvv: {selector: '#cvv', placeholder: '123'},
                      expirationDate: {selector: '#expiration-date', placeholder: 'MM/YYYY'}
                    }
                  }, function (hostedFieldsErr, hostedFieldsInstance) {
                    if (hostedFieldsErr) {
                      console.error(hostedFieldsErr);
                      return;
                    }
            
                    submit.removeAttribute('disabled');
            
                    form.addEventListener('submit', function (event) {
                      event.preventDefault();
            
                      hostedFieldsInstance.tokenize(function (tokenizeErr, payload) {
                        if (tokenizeErr) {
                          console.error(tokenizeErr);
                          return;
                        }
                        document.getElementById('nonce').value = payload.nonce;
                        document.getElementById('payment').submit();
                      });
                    }, false);
                  });
                });
              </script>
        </div>
        <span class="text-success fw-bold">Valided Card:</span>
        <span class="text-light">Card Number : 4111 1111 1111 1111</span>
        <span class="text-light">Expiration Date : 12/34</span>
        <span class="text-light">CVV : 123</span>
        <span class="text-light"><small><em>braintree by paypal</em></small></span>
    </div>
</div>

{% endblock %}

payment/templates/payment/purchasing_option.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="row">
        {% for pack in packs %}
        <div class="col">
          <div class="card border-secondary text-center bg-transparent text-success">
            <div class="card-body">
              <h4 class="card-title text text-light">{{pack.name}}</h4>
              <h6 class="card-title text-light text fw-bold">{{pack.token_amount}} Token</h6>
              <p class="card-text text-light">{{pack.description}}</p>
              <h5 class="card-title text">${{pack.total_price}}</h5>
              <a href="{% url 'payment:process' pack.id %}" class="btn btn-outline-secondary">Buy</a>
            </div>
          </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}